-- Create the database (if needed; adjust for your database system)
--CREATE DATABASE student_info_system;

-- Use the database
--USE student_info_system;  -- For MySQL; adjust for PostgreSQL (e.g., \c student_info_system) or others

--drop table students



-- Create Students table
CREATE TABLE students (
    id int PRIMARY KEY IDENTITY(1,1),  -- Auto-incrementing ID
    name VARCHAR(100) NOT NULL UNIQUE
);

-- Create Classes table
CREATE TABLE classes (
    id int PRIMARY KEY IDENTITY(1,1),
    name VARCHAR(100) NOT NULL,
    room VARCHAR(50) NOT NULL CHECK (room IN ('room_100', 'room_200', 'room_300'))
);

-- Create Enrollments table (linking students to classes)
CREATE TABLE enrollments (
    id int PRIMARY KEY IDENTITY(1,1),
    student_id INT NOT NULL,
    class_id INT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    UNIQUE(student_id, class_id)  -- Prevent duplicate enrollments
);

-- Insert classes
INSERT INTO classes (name, room) VALUES
('Microbiology', 'room_100'),
('Economics', 'room_200'),
('Cartoon Studies', 'room_300');

-- Insert 100 students with cartoon/Mickey Mouse themed names (no real PII)
INSERT INTO students (name) VALUES
('Mickey Mouse'),
('Donald Duck'),
('Goofy Goof'),
('Minnie Mouse'),
('Pluto'),
('Daisy Duck'),
('Chip'),
('Dale'),
('Clarabelle Cow'),
('Horace Horsecollar'),
('Pete'),
('Scrooge McDuck'),
('Huey Duck'),
('Dewey Duck'),
('Louie Duck'),
('Webby Vanderquack'),
('Gyro Gearloose'),
('Magica De Spell'),
('Flintheart Glomgold'),
('Bentina Beakley'),
('Duckworth'),
('Gadget Hackwrench'),
('Gadget Hackwrench Jr.'),
('Monterey Jack'),
('Zipper'),
('Gadget Hackwrench III'),
('Rescue Rangers'),
('Darkwing Duck'),
('Launchpad McQuack'),
('Gosalyn Mallard'),
('Negaduck'),
('Quackerjack'),
('Bushroot'),
('Liquidator'),
('Megavolt'),
('Steelbeak'),
('Drake Mallard'),
('Jim Starling'),
('J. Gander Hooter'),
('Tanya Vanderflame'),
('Herb Muddlefoot'),
('Binkie Muddlefoot'),
('Tank Muddlefoot'),
('Honker Muddlefoot'),
('Elmo'),
('Big Bird'),
('Cookie Monster'),
('Oscar the Grouch'),
('Grover'),
('Bert'),
('Ernie'),
('Kermit the Frog'),
('Miss Piggy'),
('Fozzie Bear'),
('Gonzo'),
('Animal'),
('Rowlf the Dog'),
('Scooter'),
('Statler'),
('Waldorf'),
('Beaker'),
('Dr. Bunsen Honeydew'),
('Swedish Chef'),
('Count von Count'),
('The Count'),
('Prairie Dawn'),
('Rosita'),
('Zoe'),
('Baby Bear'),
('Telly Monster'),
('Snuffleupagus'),
('Abby Cadabby'),
('Murray Monster'),
('Ovejita'),
('Curly Bear'),
('Papa Bear'),
('Mama Bear'),
('Goldilocks'),
('Three Little Pigs'),
('Big Bad Wolf'),
('Little Red Riding Hood'),
('Peter Pan'),
('Wendy Darling'),
('Tinker Bell'),
('Captain Hook'),
('Mr. Smee'),
('Tick-Tock Croc'),
('Lost Boys'),
('Cinderella'),
('Prince Charming'),
('Fairy Godmother'),
('Lady Tremaine'),
('Anastasia'),
('Drizella'),
('Gus'),
('Jaq'),
('Lucifer'),
('Bruno'),
('Major'),
('Perla'),
('Pumpkin'),
('Prudence'),
('Beatrice'),
('Suzy'),
('Kitty'),
('Peridot'),
('Ruby'),
('Aquamarine'),
('Topaz'),
('Amethyst'),
('Sapphire'),
('Emerald'),
('Diamond'),
('Pearl'),
('Steven Universe'),
('Garnet'),
('Amethyst SU'),
('Pearl SU'),
('Lapis Lazuli'),
('Peridot SU'),
('Bismuth'),
('Jasper'),
('Rose Quartz'),
('Greg Universe'),
('Connie Maheswaran'),
('Lion'),
('Onion'),
('Sadie Miller'),
('Lars Barriga'),
('Ronaldo Fryman'),
('Buck Dewey'),
('Jenny Pizza'),
('Kiki Pizza'),
('Nanefua Pizza'),
('Yellowtail'),
('Blue Diamond'),
('White Diamond'),
('Pink Diamond'),
('Yellow Diamond'),
('Blue Pearl'),
('Yellow Pearl'),
('Pink Pearl'),
('White Pearl'),
('Holly Blue Agate'),
('Eyeball Ruby'),
('Leggy Ruby'),
('Navy Ruby'),
('Army Ruby'),
('Doc'),
('Grumpy'),
('Happy'),
('Sleepy'),
('Bashful'),
('Sneezy'),
('Dopey'),
('Snow White'),
('The Queen'),
('The Prince'),
('The Huntsman'),
('The Magic Mirror'),
('The Seven Dwarfs');

-- Insert enrollments (distribute students evenly across the 3 classes)
-- Assuming 100 students: ~33 per class, with some extras
INSERT INTO enrollments (student_id, class_id) VALUES
-- Microbiology (room_100, class_id=1): students 1-34
(1,1),(2,1),(3,1),(4,1),(5,1),(6,1),(7,1),(8,1),(9,1),(10,1),
(11,1),(12,1),(13,1),(14,1),(15,1),(16,1),(17,1),(18,1),(19,1),(20,1),
(21,1),(22,1),(23,1),(24,1),(25,1),(26,1),(27,1),(28,1),(29,1),(30,1),
(31,1),(32,1),(33,1),(34,1),
-- Economics (room_200, class_id=2): students 35-67
(35,2),(36,2),(37,2),(38,2),(39,2),(40,2),(41,2),(42,2),(43,2),(44,2),
(45,2),(46,2),(47,2),(48,2),(49,2),(50,2),(51,2),(52,2),(53,2),(54,2),
(55,2),(56,2),(57,2),(58,2),(59,2),(60,2),(61,2),(62,2),(63,2),(64,2),
(65,2),(66,2),(67,2),
-- Cartoon Studies (room_300, class_id=3): students 68-100
(68,3),(69,3),(70,3),(71,3),(72,3),(73,3),(74,3),(75,3),(76,3),(77,3),
(78,3),(79,3),(80,3),(81,3),(82,3),(83,3),(84,3),(85,3),(86,3),(87,3),
(88,3),(89,3),(90,3),(91,3),(92,3),(93,3),(94,3),(95,3),(96,3),(97,3),
(98,3),(99,3),(100,3);